import { levelToExp } from "../util";
import { CharacterSkills } from "../types/types";
import { skill } from "./Skill";

export enum SkillNames {
  attack = "attack",
  defence = "defence",
  strength = "strength",
  hitpoints = "hitpoints",
  ranged = "ranged",
  prayer = "prayer",
  magic = "magic",
  cooking = "cooking",
  woodcutting = "woodcutting",
  fletching = "fletching",
  fishing = "fishing",
  firemaking = "firemaking",
  crafting = "crafting",
  smithing = "smithing",
  mining = "mining",
  herblore = "herblore",
  agility = "agility",
  thieving = "thieving",
  slayer = "slayer",
  farming = "farming",
  runecrafting = "runecrafting",
  hunter = "hunter",
  construction = "construction",
}

export const skills: CharacterSkills = {
  attack: skill(levelToExp(70)),
  defence: skill(levelToExp(70)),
  strength: skill(levelToExp(70)),
  hitpoints: skill(levelToExp(70)),
  ranged: skill(levelToExp(70)),
  prayer: skill(levelToExp(70)),
  magic: skill(levelToExp(70)),
  cooking: skill(),
  woodcutting: skill(),
  fletching: skill(),
  fishing: skill(levelToExp(99)),
  firemaking: skill(),
  crafting: skill(),
  smithing: skill(),
  mining: skill(),
  herblore: skill(),
  agility: skill(levelToExp(70)),
  thieving: skill(),
  slayer: skill(),
  farming: skill(),
  runecrafting: skill(),
  hunter: skill(),
  construction: skill(),
};
